#######################################################
# run_analysis.R
# author: mgk2014
# date created - 21-Jul-2014
# coursera - Getting and Cleaning Data, course project
# 
# purpose: the script reads the Samsung wearable computing test data set files
#   split across test and train data-sets, combines this data and creates a tidy-data set
# CodeBoom.md - please refer to the code book on the script transformations, and meanings of
#   the variables that are outputted into the Tidy data-set
#
# Assumptions: the scripts expects the UNZIPPED data set to be in current working directory 
#   If the data set is not found, this script stops with an error message
#
# test() : script includes a test function  that shows how to execute this script
#
#######################################################


# Free variables that will be used in the various functions scopes within this script
#   Ideally these hard coded strings may be read from a configuration file at initiation time
#
fileFeatures <- "features.txt";
fileActivities <- "activity_labels.txt";
fileTrainSet <- "train/X_train.txt";
fileTrainSubjects <- "train/subject_train.txt";
fileTrainLabels <- "train/Y_train.txt";
fileTestSet <- "test/X_test.txt";
fileTestSubjects <- "test/subject_test.txt";
fileTestLabels <- "test/Y_test.txt";

# output file director and name
outputDir <- "../output"
outputFile <- "../output/project_course3_tidydata.txt"

## run_analysis()
#   Main function: executes the logic in the following order
#   -verify data-set exists in the working directory. If any file(s) missing, aborts
#   -reads feature names, selects the mean/std columns and cleans the names
#   -reads training data, subsets to columns of interest and binds subject and features columns
#   -reads test data, subsets to columns of interest and binds subject and features columns
#   -combine the train and test data
#   -calculates means using aggregate()
#   -replaces activity numbers with activity names, using factors
#   -write the final data frame to the output file
#
# returns: TRUE if successful
#
# note: i am doing this function in different order than suggested in the assignment, so
#       as to optimize on computations. For ex - it would be faster to replace activity names on the final tidy set 
#       rather than on the read data.frame
#
run_analysis <- function()
{
    
    # Verify all necessary files exist. If even one file is missing, abort with an error
    #
    allFiles <- c(fileFeatures, fileActivities, fileTrainSet, fileTrainSubjects, fileTrainLabels, fileTestSet, fileTestSubjects, fileTestLabels);
    print("Validating project files...");
    if(!datasetExists(allFiles)){
        print("One or more files missing. Please ensure that the current working directory is the same as the location of data files. Please verify all files are present");
        print("!SCRIPT ABORTED!");
        return(NULL);
    }
    
    # Read Variable names from the source file and remove columns that are not mean and freq related
    #    Clean the column names
    #
    featureNames <- read.table(fileFeatures);
    desiredFeatures <- getDesiredFeatures(featureNames);
    columnNames <- getColumnNames(featureNames, desiredFeatures);

    # Read and consolidate training data
    print("Reading training data...")
    trainSet <- readDataSet(fileTrainSet, fileTrainSubjects, fileTrainLabels, desiredFeatures, columnNames);
        
    # Read and consolidate test data
    #
    print("Reading test data...")
    testSet <- readDataSet(fileTestSet, fileTestSubjects, fileTestLabels, desiredFeatures, columnNames);
    
    # Combine the train and test data
    #
    combinedData <- rbind(trainSet, testSet);    
    
    # Change the subject and activity column names
    colnames(combinedData)[1] <- "subject";
    colnames(combinedData)[2] <- "activity";
    
    # DEBUGGING - check the size of the new training Set
    print(paste("Train Data - ", nrow(trainSet), ncol(trainSet), format(object.size(trainSet), units = "Mb")));
    print(paste("Test Data - ", nrow(testSet), ncol(testSet), format(object.size(testSet), units = "Mb")));
    print(paste("Combined - ", nrow(combinedData), ncol(combinedData), format(object.size(combinedData), units = "Mb")));

    # Calculate the means for each subject+activity combination
    #   with the  aggregate function to do the grouping
    print("calculating means and creating tidy dataset...");
    outDF <- aggregate(combinedData, list(combinedData$subject, combinedData$activity), FUN = "mean");
    
    # Remove the two new columns generated by the aggregate function for 
    #   subect, activity. These columns already exist in the data frame
    outDF$Group.1 <- NULL;
    outDF$Group.2 <- NULL;
    
    # Change the activity values with the descriptive names as retrieved from the activity_labels.txt file
    #   Since the activities could be classified as factors, replacing factors seems like an efficient way
    #   to replace the activity numbers with names
    activityLabels <- read.table(fileActivities);
    x <- outDF$activity;
    y <- factor(x, labels = activityLabels[,2]);
    outDF$activity <- y;
    
    # Output the tidy data-set into the target output file
    #   
    print("writing output file...");
    if(!file.exists(outputDir)) dir.create(outputDir);
    write.table(outDF, outputFile, sep=",", row.names=FALSE);

    print("SUCCESS - Script complete");
    TRUE; # return TRUE for success
}


## datasetExists - helper function
#   Loops through all the file names and verifies that all of them exist. 
#   Paramters: allFiles - character vector containing file names of all files in the data set
#   Returns: False - if even file does not exist
#
datasetExists <- function(allFiles) {
    for (i in 1:length(allFiles)){
        if (!file.exists(allFiles[i])) {
            print(paste("!ERROR - Missing File", allFiles[i]));
            return(FALSE);
        }
    }
    return(TRUE);
}


## getDesiredFeatures - helper function
#   Returns the desired features (columns) by selecting the means, std columns and then removing meanFreq columns
#   Paramters: featureNames - character vector of all features names (column names) in the data set
#   Returns: integer vector containing the features of interest
#   
getDesiredFeatures <- function(featureNames) {
    meanRows <- grep("mean", featureNames[,2]);
    sdRows <- grep("std", featureNames[,2]);
    meanFreqRows <- grep("meanFreq", featureNames[,2]);
    desiredFeatures <- sort(c(meanRows, sdRows));
    desiredFeatures <- desiredFeatures[!desiredFeatures %in% meanFreqRows];
    desiredFeatures;
}


## getColumnNames - helper function
#   Cleans the columns names, by removing special characters like (, ), -, ,
#   Paramters: featureNames - character vector contain features
#   Paramters: desiredFeatures - integer vector contain indexes of features of interest
#   Returns: character vector of feature names, that are cleaned for purposes of further evaluation
#
getColumnNames <- function(featureNames, desiredFeatures){
    columnNames <- featureNames[desiredFeatures,2]
    columnNames <- gsub("\\(", "", columnNames);
    columnNames <- gsub("\\)", "", columnNames);
    columnNames <- gsub("\\,", "", columnNames);
    columnNames <- gsub("\\-", "", columnNames);
    columnNames;
}


## readDataSet - helper function
#   common function to read both train and test data set, depending on input parameters. Once the files are read, 
#       the data frame is subsetted to desired features and the subject activity columns are binded
#   Paramters: dataSetFile - file name of the data set
#   Paramters: subjectsFile - file name of subjects file
#   Paramters: labelsFile - file name of labels file
#   Paramters: desiredFeatures - integer vector containing desired features
#   Paramters: columnNames - character vector contain feature names
#   Returns: data frame of the newly read and combined data-set
#
readDataSet <- function(dataSetFile, subjectsFile, labelsFile, desiredFeatures, columnNames){
    dataSet <- read.table(dataSetFile);
    subjects <- read.table(subjectsFile);
    labels <- read.table(labelsFile);
    dataSet <- dataSet[,desiredFeatures];
    colnames(dataSet) <- columnNames;
    dataSet <- cbind(subjects, labels, dataSet);
    dataSet;
}

## test(): test function
#   Function provides a test script to set the working diretory and execute the script
#
test <- function()
{
    #Set working folder to where the files are expected.  
    folder <- "~/Documents/_Certifications/Data Science/3. Getting and Cleaning Data/Project/UCI HAR Dataset"
    setwd(folder);
    
    # Run the main script
    system.time(run_analysis());
}
